/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crypto_shop;

import EnCrypto.Crypto;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Fileform extends javax.swing.JFrame  {
 File selectedFile;
 String fileName;
 int enkey;
 
 
     Connection con=null;
    PreparedStatement pst=null;
 
    /**
     * Creates new form Fileform
     */
 
    public Fileform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jFChoose = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        Jtfkey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("              Encrypt File");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton2.setText("START");
        jButton2.setToolTipText("Start Encrypting the file");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jFChoose.setApproveButtonText("Open");
        jFChoose.setDialogTitle("");
        jFChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFChooseActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        jLabel2.setText("Status  :");

        status.setText("Welcome...");

        Jtfkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfkeyActionPerformed(evt);
            }
        });

        jLabel3.setText("Key:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jtfkey, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jFChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtfkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFChooseActionPerformed
        // TODO add your handling code here:
        
      
        
        selectedFile=jFChoose.getSelectedFile();
        //jFChoose.showOpenDialog(null);
        fileName=selectedFile.getName();
        System.out.print(selectedFile.getName());
        JOptionPane.showMessageDialog(null,"File Opened successfully..");

        status.setText("File selected"); 
    }//GEN-LAST:event_jFChooseActionPerformed

 @SuppressWarnings("empty-statement")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        
//        try (BufferedReader br = new BufferedReader(new FileReader(selectedFile))) { 
//         
//      String sCurrentLine;
//         while ((sCurrentLine = br.readLine()) != null) {
//				System.out.println(sCurrentLine);
//			}  
//      } catch (IOException e) {
//         e.printStackTrace();
// }


        Crypto objCrypto=new Crypto();
        char ch;
        
        //enkey=3;
        if(Jtfkey.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter key first:");
        }
        else
             enkey=Integer.parseInt(Jtfkey.getText());
      
        try {
              FileInputStream fis = new FileInputStream(selectedFile);

              int counter=0;
              System.out.println(selectedFile.getParentFile());
              System.out.println(selectedFile.getParent());
              System.out.println(selectedFile.getPath()); 
              String path=new String(selectedFile.getPath());
              path=path.replace(selectedFile.getName(), "temp.txt");
              System.out.println(path);
              
              File tempFile=new File(path);
              tempFile.createNewFile();
              
              FileWriter fw=new FileWriter(path,true);
              
              char current;
              while (fis.available() > 0) {
                current = (char) fis.read();
                counter++;
                
                if(counter>0)
                {
                    System.out.print(current);
                    ch=objCrypto.retEncrypt(current,enkey);
                
                status.setText("Encrypting...");
                //System.out.print(ch);
                fw.append(ch);
                }       
                status.setText("Finalizing encryption process");
              }
              
              fis.close();
              fw.close();
              
              selectedFile.delete();
              tempFile.renameTo(selectedFile);
              
              status.setText("Ending up with files");
            } catch (IOException e) {
              e.printStackTrace();
              status.setText("Error...");
            }

        
        try
                        {
                            con=new DBConnect().getConnect();
                            
                                pst=con.prepareStatement("insert into filetb values(?,?)");
                                pst.setString(1,fileName);
                                pst.setInt(2,enkey);
                                int result=pst.executeUpdate();

                                if(result>0)
                                {
                                    System.out.println("Success in File Table updation");
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null,"File table updation error!");
                                }
                             

                        }
                        catch(Exception ex)
                        {
                            JOptionPane.showMessageDialog(null, ex);
                        }
        
        
        
        
        status.setText("Encryption successfull...");
        jButton2.setEnabled(false);   
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JtfkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfkeyActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(true);
    }//GEN-LAST:event_JtfkeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fileform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fileform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fileform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fileform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fileform().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jtfkey;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
